let mapleader = " "
set nocompatible
set modifiable
set number
set signcolumn=yes
set fileencodings=utf-8,sjis,euc-jp,latin
set encoding=UTF-8
set title
set autoindent
set background=dark
set nobackup
set hlsearch
set showcmd
set cmdheight=1
set laststatus=2
set scrolloff=10
set expandtab
set omnifunc=syntaxcomplete#Complete
set hidden
set noerrorbells
set relativenumber
set nohlsearch
set nuw=4
set nowrap
set termguicolors
set tabstop=2
set shiftwidth=2
set expandtab
filetype plugin on
